# Generated by Django 4.0.3 on 2022-03-30 06:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=210, populate_from='title'),
        ),
    ]
