# Generated by Django 4.0.3 on 2022-03-30 06:49

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=1, editable=False, max_length=200, populate_from='name'),
            preserve_default=False,
        ),
    ]
