# Generated by Django 4.0.3 on 2022-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_desc_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
