# Generated by Django 4.0.3 on 2022-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
